### ISSUE TITLE
APIError / Unicode error listing records

### ISSUE THREAD

**Issue by aleontiev** [Clever/clever-python#45]
I am trying to enumerate through students and have run into a student with a unicode character in their name. This triggers a decode error on [this line](https://github.com/Clever/clever-python/blob/master/clever/__init__.py#L285) which is masked and an `APIError` is raised instead.

Stack trace with PII redacted:

```
>>> clever.Student.all(where=json.dumps({'sis_id': 'XXX'}))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/altschool/clever-sync.src/src/clever/clever/__init__.py", line 711, in all
    return list(cls.iter(auth, **params))
  File "/usr/local/altschool/clever-sync.src/src/clever/clever/__init__.py", line 725, in iter
    response, auth = requestor.request('get', url, params)
  File "/usr/local/altschool/clever-sync.src/src/clever/clever/__init__.py", line 220, in request
    resp = self.interpret_response(res)
  File "/usr/local/altschool/clever-sync.src/src/clever/clever/__init__.py", line 298, in interpret_response
    (rbody, rcode), rbody, rcode)
APIError: Invalid response body from API: {"data":[{"data":{"dob":"","last_modified":"2017-08-16T12:58:15.051Z","grade":"1","district":"XXX","student_number":"XXX","created":"2017-07-07T18:16:34.802Z","credentials":{"district_username":"XXXôXXX"},"hispanic_ethnicity":"","location":{"zip":"","address":"","city":"","lat":"","lon":"","state":""},"name":{"first":"XXXôXXX","last":"XXX","middle":""},"sis_id":"XXX","email":"","race":"","school":"XXX","state_id":"","gender":"","id":"XXX"},"uri":"/v1.1/students/XXX"}],"paging":{"current":1,"total":1,"count":1},"links":[{"rel":"self","uri":"/v1.1/students?where=%7B%22sis_id%22%3A%20%22XXX%22%7D&limit=1000"}]} (HTTP response code was 200)
```

Note the value of `name.first` and `credentials.district_username` include the character "ô"

**Comment by aleontiev** [comment]
I was able to fix this in a fork with [this simple change](https://github.com/AltSchool/clever-python/commit/aeaea79c3032fee9f85bd6e8900b5bf6ef273acc) but I am not sure that this won't break some other edge cases.

**Comment by meliaj** [comment]
Thanks for letting us know! I'm glad you came to a solution as well.

I also found that explicitly setting the encoding to UTF-8 works as well:
```
rbody.decode('utf-8')
```
