### ISSUE TITLE
Failing module import in python 3.6

### ISSUE THREAD

**Issue by incidentist** [Clever/clever-python#53]
Importing clever into any script fails when running Python 3.6.4. 

To reproduce:
1. Create a file whose contents consist of `import clever`
2. Run that file with python 3.6.4

Expected result: Script should exit cleanly

Result:
`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import clever
  File "/usr/local/lib/python3.6/site-packages/clever/__init__.py", line 17, in <module>
    from .models.bad_request import BadRequest
  File "/usr/local/lib/python3.6/site-packages/clever/models/__init__.py", line 69, in <module>
    from .contacts_updated import ContactsUpdated
  File "/usr/local/lib/python3.6/site-packages/clever/models/contacts_updated.py", line 17, in <module>
    import event
ModuleNotFoundError: No module named 'event'`

I haven't tried this in other python versions.

**Comment by incidentist** [comment]
The root cause here is that some files do implicit relative importing of the `event` module, and implicit relative imports are not supported in Python 3.

**Comment by meliaj** [comment]
Resolved

**Comment by meliaj** [comment]
Resolved and published
